services:
  #ngix
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #php
  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/app
  
  #database
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql/contenido.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: docker-php
volumes:
  mysqldata: